insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Audit et stratégie Web', 1, 1, 1, '500.00', '1.00', '500.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Design et maquettes (5 pages)', 1, 2, 2, '1500.00', '1.00', '1500.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Développement Front-end', 1, 3, 3, '1000.00', '1.00', '1000.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Intégration CMS WordPress', 1, 4, 4, '750.00', '1.00', '750.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Architecture WooCommerce', 2, 5, 1, '1500.00', '1.00', '1500.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Design boutique (20 pages)', 2, 6, 2, '2000.00', '1.00', '2000.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Intégration 100 produits', 2, 7, 3, '1500.00', '1.00', '1500.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Configuration Stripe + test paiement', 2, 8, 4, '1000.00', '1.00', '1000.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Formation client (2h)', 2, 9, 5, '666.67', '1.00', '666.67');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Création 3 concepts logo', 3, 10, 1, '600.00', '1.00', '600.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Charte graphique 20 pages', 3, 11, 2, '300.00', '1.00', '300.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Supports imprimés (design)', 3, 12, 3, '100.00', '1.00', '100.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Design Landing Page', 4, 13, 1, '800.00', '1.00', '800.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Développement + Animations', 4, 14, 2, '700.00', '1.00', '700.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Intégration formulaire lead', 4, 15, 3, '166.67', '1.00', '166.67');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Shooting photo 4h', 5, 16, 1, '800.00', '1.00', '800.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Retouche 50 photos', 5, 17, 2, '300.00', '1.00', '300.00');
insert into `devis_lignes` (`designation`, `devis_id`, `id`, `ordre_affichage`, `prix_unitaire`, `quantite`, `total`) values ('Galerie web + optimisation images', 5, 18, 3, '150.00', '1.00', '150.00');
